---
- name: Add repo
  yum_repository: name=ce-stable description='ownCloud Server Version stable (CentOS_7)' enabled=no baseurl=http://download.owncloud.org/download/repositories/stable/CentOS_7 gpgcheck=yes gpgkey=http://download.owncloud.org/download/repositories/stable/CentOS_7/repodata/repomd.xml.key state=present owner=root group=root mode=0644

- name: Install package
  yum: name=owncloud-files state=present enablerepo=ce-stable

- name: Check if data directory is nfs mounted
  command: stat --file-system --format=%T {{owncloud_data_path}}
  changed_when: false
  failed_when: false
  check_mode: no
  register: owncloud__r_mount
  become: yes
  become_user: '{{owncloud_user}}'

- name: Make sure data directory exists when it is nfs mounted
  file: path='{{owncloud_data_path}}' state=directory mode=0750
  become: yes
  become_user: '{{owncloud_user}}'
  when: owncloud__r_mount.stdout == 'nfs'

- name: Make sure data directory exists when it is not nfs mounted
  file: path='{{owncloud_data_path}}' state=directory mode=0750 owner={{owncloud_user}} group={{owncloud_group}}
  when: owncloud__r_mount.stdout != 'nfs'

- name: Find owncloud version
  command: php -r 'include "version.php"; echo join(".", $OC_Version);'
  args:
    chdir: '{{owncloud_path}}'
  register: owncloud__r_version
  changed_when: false
  check_mode: no

- name: Drop configuration file
  template: dest={{owncloud_path}}/config/config.php src=config.php.j2 mode=0640 owner={{owncloud_user}} group={{owncloud_group}}

- block:
    - name: Check if owncloud has been initialized
      stat: path={{owncloud_data_path}}/.ocdata
      register: owncloud__r_init
      become: yes
      become_user: '{{owncloud_user}}'

    - name: Mark instance not installed
      lineinfile: dest={{owncloud_path}}/config/config.php regexp="^  'installed' =>" state=absent
      when: not owncloud__r_init.stat.exists

    - name: Initialize
      command: php occ maintenance:install --data-dir='{{owncloud_data_path}}' --admin-user '{{owncloud_admin}}' --admin-pass '{{owncloud_admin_pass}}' --database '{{owncloud_db_type}}' --database-name '{{owncloud_db_name}}' --database-host '{{owncloud_db_host}}' --database-user '{{owncloud_db_user}}' --database-pass '{{owncloud_db_pass}}'
      args:
        chdir: '{{owncloud_path}}'
      become: yes
      become_user: '{{owncloud_user}}'
      when: not owncloud__r_init.stat.exists
  when: hostvars[owncloud_app_servers[0]].ansible_fqdn == ansible_fqdn

- include: user_ldap.yml
  when: hostvars[owncloud_app_servers[0]].ansible_fqdn == ansible_fqdn

- include: memcache.yml

- include: logging.yml

- include: theme.yml

- include: appstore.yml

- include: background_jobs.yml

- include: email_server.yml

- include: antivirus.yml

- include: documents.yml

- include: fix_permissions.yml
